### ISSUE TITLE
Error caused by go1.6 cgo major change

### ISSUE THREAD

**Issue by everplus** [oskca/sciter#15]
Run example error

```
D:\>go version
go version go1.6 windows/amd64
```

```
D:\Working\Go\Packages\src\github.com\oskca\sciter\examples\handlers>handlers.exe a.html
2016/02/23 13:48:08 Sciter Version: 30003 10007
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
panic(0x7d0620, 0xc0824205c0)
        c:/go/src/runtime/panic.go:464 +0x3f4
github.com/oskca/sciter.(*Sciter).SetCallback(0xc08209dda0, 0xc08239a6f0)
        D:/Working/Go/Packages/src/github.com/oskca/sciter/sciter.go:222 +0xc8
github.com/oskca/sciter/rice.HandleDataLoad(0xc08209dda0)
        D:/Working/Go/Packages/src/github.com/oskca/sciter/rice/rice.go:73 +0x40
main.main()
        D:/Working/Go/Packages/src/github.com/oskca/sciter/examples/handlers/handlers.go:116 +0x3fe
```

**Comment by everplus** [comment]
Go Version 1.5.3 is OK

**Comment by oskca** [comment]
This is the result of the `major cgo change` happend in go1.6 release:
   
    The major change is the definition of rules for sharing Go pointers with C code, ... , 
    Briefly, Go and C may share memory allocated by Go when a pointer to that memory is passed to 
    C as part of a cgo call, 
    provided that the memory itself contains no pointers to Go-allocated memory

I'm working on this
