### ISSUE TITLE
invoke callback crash

### ISSUE THREAD

**Issue by everplus** [oskca/sciter#16]
html

```
<div>
	<button id="btn">Click Me</button>
</div>
<script type="text/tiscript">
function callback(abc){
	view.msgbox(#information,abc);
}

$(#btn).on("click",function(){
	view.getNetInformation(1,"test",callback);
});
</script>
```

go

```
package main

import (
	"log"

	"github.com/oskca/sciter"
	"github.com/oskca/sciter/window"
)

func main() {
	w, err := window.New(sciter.SW_TITLEBAR|sciter.SW_RESIZEABLE|sciter.SW_CONTROLS|sciter.SW_MAIN|sciter.SW_ENABLE_DEBUG, nil)
	if err != nil {
		log.Fatal("Create Window Error: ", err)
	}
	w.LoadFile("resource/index.html")
	setEventHandler(w)
	w.Show()
	w.Run()
}

func setEventHandler(w *window.Window) {
	w.DefineFunction("getNetInformation", func(args ...*sciter.Value) *sciter.Value {
		log.Println("Args Length:", len(args))
		log.Println("Arg 0:", args[0], args[0].IsInt())
		log.Println("Arg 1:", args[1], args[1].IsString())
		log.Println("Arg 2:", args[2], args[2].IsFunction())
		fn := args[2]
		fn.Invoke(sciter.NullValue(), "[Native Script]", sciter.NewValue("OK"))
		ret := sciter.NewValue()
		ret.Set("ip", sciter.NewValue("127.0.0.1"))
		return ret
	})
}
```

output

```
2016/02/23 16:16:34 Args Length: 3
2016/02/23 16:16:34 Arg 0: 1 true
2016/02/23 16:16:34 Arg 1: test true
2016/02/23 16:16:34 Arg 2:  false
runtime: newstack sp=0x12183ea0 stack=[0x12180000, 0x12183fd8]
	morebuf={pc:0x426408 sp:0x12183ea4 lr:0x0}
	sched={pc:0x42755f sp:0x12183ea0 lr:0x0 ctxt:0x0}
syscall.Syscall(0x7600788b, 0x1, 0x12183f30, 0x0, 0x0, 0x0, 0xf, 0x0)
	c:/go/src/runtime/syscall_windows.go:128 +0x4a
github.com/lxn/win.DispatchMessage(0x12183f30, 0x0)
	D:/Working/Go/Packages/src/github.com/lxn/win/user32.go:1924 +0x43
github.com/oskca/sciter/window.(*Window).Run(0x12170100)
	D:/Working/Go/Packages/src/github.com/oskca/sciter/window/window_windows.go:58 +0x7c
main.main()
	D:/Working/Go/NetworkTools/src/NetworkTools/main.go:18 +0x17e
fatal error: runtime: stack split at bad time

runtime stack:
runtime.throw(0x52c2c0, 0x20)
	c:/go/src/runtime/panic.go:527 +0x7f
runtime.newstack()
	c:/go/src/runtime/stack1.go:694 +0x505
runtime.morestack()
	c:/go/src/runtime/asm_386.s:336 +0x6f

goroutine 1 [syscall, locked to thread]:
runtime.throw(0x532540, 0x2d)
	c:/go/src/runtime/panic.go:521 +0x8 fp=0x12183eb0 sp=0x12183ea4
runtime.exitsyscall(0x0)
	c:/go/src/runtime/proc1.go:1978 +0x52 fp=0x12183ecc sp=0x12183eb0
runtime.cgocall(0x44c250, 0x5adc5c, 0x0)
	c:/go/src/runtime/cgocall.go:122 +0x125 fp=0x12183ee4 sp=0x12183ecc
syscall.Syscall(0x7600788b, 0x1, 0x12183f30, 0x0, 0x0, 0x0, 0xf, 0x0)
	c:/go/src/runtime/syscall_windows.go:128 +0x4a fp=0x12183ef8 sp=0x12183ee4
github.com/lxn/win.DispatchMessage(0x12183f30, 0x0)
	D:/Working/Go/Packages/src/github.com/lxn/win/user32.go:1924 +0x43 fp=0x12183f1c sp=0x12183ef8
github.com/oskca/sciter/window.(*Window).Run(0x12170100)
	D:/Working/Go/Packages/src/github.com/oskca/sciter/window/window_windows.go:58 +0x7c fp=0x12183f50 sp=0x12183f1c
main.main()
	D:/Working/Go/NetworkTools/src/NetworkTools/main.go:18 +0x17e fp=0x12183fa0 sp=0x12183f50
runtime.main()
	c:/go/src/runtime/proc.go:111 +0x234 fp=0x12183fc8 sp=0x12183fa0
runtime.goexit()
	c:/go/src/runtime/asm_386.s:1662 +0x1 fp=0x12183fcc sp=0x12183fc8

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	c:/go/src/runtime/asm_386.s:1662 +0x1
```

Is there any problem with my code?

**Comment by everplus** [comment]
App crash when click button

log.Println("Arg 2:", args[2], args[2].IsFunction())
2016/02/23 16:16:34 Arg 2:  false

Why arg[2] is not  a function?

**Comment by oskca** [comment]
arg[2] is first an object and then a functiion, thus the function `Value.IsIsObjecFunction` should be used :smile:

**Comment by everplus** [comment]
IsObjecFunction or IsObjectFunction?

**Comment by oskca** [comment]
Should be `IsObjectFunction` :smile:
